before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: killer-q-darwin
  hooks:
    pre: packr2
    post: packr2 clean
  env:
  - CGO_ENABLED=1
  goos:
    - darwin
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/sheer-heart-attack.version={{.Version}} -X github.com/k1LoW/sheer-heart-attack.commit={{.FullCommit}} -X github.com/k1LoW/sheer-heart-attack.date={{.Date}} -X github.com/k1LoW/sheer-heart-attack/version.Version={{.Version}}
-
  id: killer-q-linux
  hooks:
    pre: packr2
    post: packr2 clean
  env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/sheer-heart-attack.version={{.Version}} -X github.com/k1LoW/sheer-heart-attack.commit={{.FullCommit}} -X github.com/k1LoW/sheer-heart-attack.date={{.Date}} -X github.com/k1LoW/sheer-heart-attack/version.Version={{.Version}}
archives:
-
  id: killer-q-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
nfpms:
  -
    id: killer-q-nfpms
    name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - killer-q-linux
    homepage: https://github.com/k1LoW/sheer-heart-attack
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: sheer-heart-attack is a debugging tool that can execute any command on process/host metrics trigger.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
